name: angular2_rbi
description: Making MDL dynamic components work with Angular 2
version: 0.1.0
author: Jim Washington <washington.jim@gmail.com>
homepage: https://github.com/jwashin/angular2-rbi-dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  angular2: ">=2.0.0-beta.0 <3.0.0"

transformers:
- angular2:
    entry_points: [lib/directives.dart]
